// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5571.BobbyTShirtLauncher;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainCANTalon1;
    public static CANTalon driveTrainCANTalon2;
    public static CANTalon driveTrainCANTalon3;
    public static CANTalon driveTrainCANTalon4;
    public static RobotDrive driveTrainRobotDrive41;
    public static Compressor pneumaticsCompressor1;
    public static Solenoid pneumaticsRightTubeSolenoid;
    public static Solenoid pneumaticsLeftTubeSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainCANTalon1 = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 1", driveTrainCANTalon1);
        
        driveTrainCANTalon2 = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 2", driveTrainCANTalon2);
        
        driveTrainCANTalon3 = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 3", driveTrainCANTalon3);
        
        driveTrainCANTalon4 = new CANTalon(4);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 4", driveTrainCANTalon4);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainCANTalon1, driveTrainCANTalon2,
              driveTrainCANTalon3, driveTrainCANTalon4);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        pneumaticsCompressor1 = new Compressor(0);
        
        
        pneumaticsRightTubeSolenoid = new Solenoid(0, 2);
        LiveWindow.addActuator("Pneumatics", "RightTubeSolenoid", pneumaticsRightTubeSolenoid);
        
        pneumaticsLeftTubeSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "LeftTubeSolenoid", pneumaticsLeftTubeSolenoid);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
